In [1]:
# import the tensorflow library

import tensorflow as tf

In [4]:
# Creates a rank-0 tensor, which is just a scalar (a single value).

rank_0_tensor = tf.constant(4)
# prints the tensor object itself.

print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
# Create a rank 1 tensor (a list of values)

rank_1_tensor = tf.constant([10, 20, 30])  

# Display the tensor, its shape, and data type

print(rank_1_tensor)  

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [6]:
# Create a rank 2 tensor (table of values)

rank_2_tensor = tf.constant([  

    [1, 2, 3],                   # First row of the matrix

    [4, 5, 6]                    # Second row of the matrix

])



 # Display the tensor, its shape, and data type

print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
import tensorflow as tf  # Import TensorFlow



# Create a rank 3 tensor (3D tensor)

rank_3_tensor = tf.constant([

    [  # First block (Block 1)

        [0, 1, 2, 3, 4],      # Row 1

        [5, 6, 7, 8, 9]       # Row 2

    ],

    [  # Second block (Block 2)

        [10, 11, 12, 13, 14], # Row 1

        [15, 16, 17, 18, 19] # Row 2

    ],

    [  # Third block (Block 3)

        [20, 21, 22, 23, 24], # Row 1

        [25, 26, 27, 28, 29] # Row 2

    ]

])



print(rank_3_tensor)  # Display the tensor

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [8]:
#Print the first block

print(rank_3_tensor[0])

#Print the first row of the block

print(rank_3_tensor[0][0])

#Print the first value

print(rank_3_tensor[0][0][0])

tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
