In [1]:
# import the tensorflow library
import tensorflow as tf


#Create tensor that represents 3 students with marks for 4 courses.
rank_2_tensor = tf.constant([  

    [90, 70, 88,92],                   # First student

    [99, 79, 92,91],                   # Second student
    [70, 77, 88,66]                    # thired student
                                       

])



 # Display the tensor, its shape, and data type

print(rank_2_tensor)

tf.Tensor(
[[90 70 88 92]
 [99 79 92 91]
 [70 77 88 66]], shape=(3, 4), dtype=int32)


In [2]:
#Display all the marks for the first student.
print(rank_2_tensor[0])

tf.Tensor([90 70 88 92], shape=(4,), dtype=int32)


In [3]:
#Display the mark for the first course of the first student.
print(rank_2_tensor[0][0])

tf.Tensor(90, shape=(), dtype=int32)


In [4]:
#Display the marks of the first course of the second student.
print(rank_2_tensor[1][0])

tf.Tensor(99, shape=(), dtype=int32)
